020621
frc-6901/2021-Code pull request #6
Opened 2021-02-07 00:26 UTC by hvaranasi9

Included subclass as discussed with Mateo. For some reason, the existing pulled version of Constants.java file in master base of the frc repository did not show the subclass. So, re-pulling.

2021-02-07 19:13 UTC, hvaranasi9 commented
Matteo,

Please view the comments that I wrote in the Robot.java file [in the autonomousPeriodic method] and provide advice accordingly. Thank you!

2021-02-08 06:19 UTC, Piphi5 commented
In order for you to use the Xbox Controller's bumpers, you need to initialize the Xbox Controller Object. This object contains methods for reading if the button was pressed. For reference, [here](https://first.wpi.edu/wpilib/allwpilib/docs/release/java/edu/wpi/first/wpilibj/XboxController.html) is a link to the Xbox Controller Documentation. 

Let me know if you have any other questions.

2021-02-08 06:23 UTC, Piphi5 requested changes

2021-02-08 06:23 UTC, Piphi5 commented on src/main/java/frc/robot/Robot.java
> +    }
This should be within teleopPeriodic

2021-02-08 06:23 UTC, Piphi5 commented on src/main/java/frc/robot/Robot.java
> +  private VictorSPX mMotor = new VictorSPX(Constants.IntakeConstants.VictorSPXPort);
I would suggest a more descriptive name (e.g. mIntakeMotor)

2021-02-08 06:23 UTC, Piphi5 commented on src/main/java/frc/robot/Robot.java
> +    }
Make sure you set the motor speed to zero when nothing is pressed

2021-02-08 06:23 UTC, Piphi5 commented on src/main/java/frc/robot/Robot.java
> +      mMotor.setSpeed(Constants.IntakeConstants.kIntakePower);
A VictorSPX does not have a setSpeed method. [Here ](https://www.ctr-electronics.com/downloads/api/java/html/classcom_1_1ctre_1_1phoenix_1_1motorcontrol_1_1can_1_1_victor_s_p_x.html) is the documentation regarding the VictorSPX

2021-02-08 07:02 UTC, Piphi5 commented on src/main/java/frc/robot/Robot.java
> +
Don't forget to import the XboxController and VIctorSPX code

2021-02-08 23:38 UTC, closed without merging